---
sudo: false
language: ruby
bundler_args: --without development system_tests
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
matrix:
  exclude:
  - rvm: 2.1.5
    env: PUPPET_VERSION="~> 3.4.0"
